name: Build Go Program

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-application:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write

    steps:

      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Build Go
        run: "go build ."

      - name: Run program
        run: "./scratch"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scratch
          path: ./scratch

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "scratch*"
          tag: v1.0.1
          commit: master
